version: "3"

services:
  database:
    image: "postgres:9.5"
    ports:
      - "5432:5432"

  redis:
    image: "redis:3"
    ports:
      - "6379:6379"

  bot:
    build:
      context: .
    volumes:
      - ".:/app"
    depends_on:
      - "database"
    environment:
      DATABASE_URL: postgres://postgres@database/fraggers_development
      DISCORD_ENV:  development
